# Puerto de la aplicación
quarkus.http.port=8090

# Base path para todos los servicios CXF
quarkus.cxf.path=/soap



# Endpoints SOAP restantes gestionados automáticamente
quarkus.cxf.endpoint."/billath".implementor=com.avvillas.infrastructure.api.soap.controller.BillController
quarkus.cxf.endpoint."/pmtnotificationath".implementor=com.avvillas.infrastructure.api.soap.controller.PmtNotificationController
quarkus.cxf.endpoint."/pmtrollbackath".implementor=com.avvillas.inf""rastructure.api.soap.controller.PmtRollbackController
quarkus.cxf.endpoint."/consultbillavvillas".implementor=com.avvillas.infrastructure.api.soap.controller.ConsultBillAvVillasController
quarkus.cxf.endpoint."/paybillavvillas".implementor=com.avvillas.infrastructure.api.soap.controller.PayBillAvVillasController

# Logging de CXF detallado (para ver REQ_IN y RESP_OUT)
quarkus.log.category."org.apache.cxf.interceptor".level=INFO
quarkus.log.category."org.apache.cxf.interceptor".handlers=DEFAULT
quarkus.log.category."org.apache.cxf.services".level=INFO
quarkus.log.category."org.apache.cxf.services".handlers=DEFAULT

# Base de datos PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgresWsdev
quarkus.datasource.reactive.url=postgresql://localhost:5432/ws_avvillas

# CORS (habilitado para todos

# Config CORS
quarkus.http.cors=true
quarkus.http.cors.origins=*