create table transaction_history
(
    id                integer generated by default as identity
        constraint "TRANSACTION_HISTORY_pk"
            primary key,
    request_id        varchar,
    search_type       varchar,
    invoice_id        varchar,
    invoice_card      varchar,
    paid_value        numeric,
    number_status     integer,
    message_status    varchar,
    request_date      timestamp,
    who_send_petition varchar,
    str_web_service   varchar,
    exception         varchar
);

comment on column transaction_history.id is 'Identificador unico de la transaccion';

comment on column transaction_history.request_id is 'Identificador de la solicitud';

comment on column transaction_history.search_type is 'Tipo de busqueda de una factura';

comment on column transaction_history.invoice_id is 'Numero de factura o cedula de la solicitud';

comment on column transaction_history.number_status is 'Numero de solicitud cuando se consulta una factura o numero de respuesta a la solicitud';

comment on column transaction_history.message_status is 'Mensaje de respuesta a la solicitud';

comment on column transaction_history.request_date is 'Fecha de la solicitud y respuesta';

comment on column transaction_history.exception is 'Mensaje de excepcion cuando atlante falle';

comment on column transaction_history.paid_value is 'Valor total de la factura';

comment on column transaction_history.who_send_petition is 'Indica que entidad envia la peticion, si el banco o la universidad';

comment on column transaction_history.str_web_service is 'Indica a que web service pertenece la peticion';

comment on column transaction_history.invoice_card is 'Cedula a la que pertenece una factura';
